config:
  send_anonymous_usage_stats: false
sm_test_project:
  target: default
  outputs:
    default:
      dataset: "{{ env_var('OUTPUT_DATASET') }}"
      keyfile: ./service_account.json
      location: US
      method: service-account
      priority: interactive
      project: wise-weaver-282922
      threads: 6
      timeout_seconds: 600
      type: bigquery

